#!/usr/bin/env python3
"""traderie_disk_inventory.py — Read-only disk inventory for Traderie artifacts.

Reports file sizes, counts, dates per retention class. No file content reading.
Dry-run by default (--dry-run, default true). No destructive mode in this task.
Output: JSON report to stdout.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"

SNAPSHOTS_RAW = DATA_DIR / "snapshots" / "raw" / "traderie"
SNAPSHOTS_NORMALIZED = DATA_DIR / "snapshots" / "normalized" / "traderie"
HISTORY_DIR = DATA_DIR / "history" / "traderie"
PRODUCTS_DIR = DATA_DIR / "products"
RESEARCH_DIR = DATA_DIR / "research"
PRICES_DIR = DATA_DIR / "prices"
RAW_DATA_DIR = DATA_DIR / "raw"
EXTERNAL_DIR = DATA_DIR / "external"
NORMALIZED_DIR = DATA_DIR / "normalized"

SEGMENTS = ["pc_sc_l", "pc_sc_nl", "pc_hc_l", "pc_hc_nl"]


def _safe_stat(path: Path) -> os.stat_result | None:
    try:
        return path.stat()
    except OSError:
        return None


def _walk_files(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return [p for p in root.rglob("*") if p.is_file()]


def _summarize_class(label: str, files: list[Path]) -> dict:
    if not files:
        return {
            "class": label,
            "file_count": 0,
            "total_size_bytes": 0,
            "total_size_human": "0 B",
            "oldest_file": None,
            "newest_file": None,
            "oldest_mtime": None,
            "newest_mtime": None,
            "estimated_daily_growth_bytes": 0,
            "estimated_daily_growth_human": "0 B",
        }

    sizes = []
    mtimes = []
    for f in files:
        st = _safe_stat(f)
        if st:
            sizes.append(st.st_size)
            mtimes.append(st.st_mtime)

    total = sum(sizes)
    oldest_ts = min(mtimes) if mtimes else None
    newest_ts = max(mtimes) if mtimes else None

    oldest_dt = datetime.fromtimestamp(oldest_ts, tz=timezone.utc) if oldest_ts else None
    newest_dt = datetime.fromtimestamp(newest_ts, tz=timezone.utc) if newest_ts else None

    # Daily growth estimate: divide total by span in days
    # Minimum 1 day span to avoid division by zero on same-timestamp files.
    # Files updated as a batch (e.g. history JSONL regenerated by pipeline) may
    # all share the same mtime — report "insufficient_data" in that case.
    if oldest_ts is not None and newest_ts is not None:
        span_days = (newest_ts - oldest_ts) / 86400
        if span_days < 1.0:
            daily_growth = None
            daily_growth_note = "insufficient_data — files span less than 1 day"
        else:
            daily_growth = total / span_days
            daily_growth_note = f"extrapolated from {span_days:.1f}-day span"
    else:
        daily_growth = None
        daily_growth_note = "no files"

    return {
        "class": label,
        "file_count": len(files),
        "total_size_bytes": total,
        "total_size_human": _human_size(total),
        "oldest_file": str(files[0]) if oldest_dt else None,
        "newest_file": str(files[-1]) if newest_dt else None,
        "oldest_mtime": oldest_dt.isoformat() if oldest_dt else None,
        "newest_mtime": newest_dt.isoformat() if newest_dt else None,
        "estimated_daily_growth_bytes": round(daily_growth, 2) if daily_growth is not None else None,
        "estimated_daily_growth_human": _human_size(daily_growth) if daily_growth is not None else daily_growth_note,
    }


def _human_size(bytes_val: float) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if abs(bytes_val) < 1024.0:
            return f"{bytes_val:.1f} {unit}"
        bytes_val /= 1024.0
    return f"{bytes_val:.1f} PB"


def _collect_traderie_raw_snapshots() -> list[Path]:
    """Collect raw snapshot files (response.json) under the traderie source."""
    files = []
    for seg in SEGMENTS:
        seg_dir = SNAPSHOTS_RAW / seg
        if seg_dir.exists():
            for f in seg_dir.rglob("*.json"):
                files.append(f)
    return files


def _collect_traderie_normalized_snapshots() -> list[Path]:
    """Collect normalized snapshot files under the traderie source."""
    files = []
    for seg in SEGMENTS:
        seg_dir = SNAPSHOTS_NORMALIZED / seg
        if seg_dir.exists():
            for f in seg_dir.rglob("*.json"):
                files.append(f)
    return files


def _collect_history() -> list[Path]:
    files = []
    for seg in SEGMENTS:
        seg_dir = HISTORY_DIR / seg
        if seg_dir.exists():
            for f in seg_dir.iterdir():
                if f.is_file():
                    files.append(f)
    return files


def _collect_products() -> list[Path]:
    return [f for f in PRODUCTS_DIR.iterdir() if f.is_file()] if PRODUCTS_DIR.exists() else []


def _collect_research() -> list[Path]:
    return _walk_files(RESEARCH_DIR)


def _collect_prices() -> list[Path]:
    return [f for f in PRICES_DIR.iterdir() if f.is_file()] if PRICES_DIR.exists() else []


def _collect_raw() -> list[Path]:
    return [f for f in RAW_DATA_DIR.iterdir() if f.is_file()] if RAW_DATA_DIR.exists() else []


def build_report() -> dict:
    raw_snapshots = _collect_traderie_raw_snapshots()
    normalized_snapshots = _collect_traderie_normalized_snapshots()
    history_files = _collect_history()
    product_files = _collect_products()
    research_files = _collect_research()
    price_files = _collect_prices()
    raw_data_files = _collect_raw()

    classes = [
        _summarize_class("raw_snapshot", raw_snapshots),
        _summarize_class("normalized_snapshot", normalized_snapshots),
        _summarize_class("history_jsonl", history_files),
        _summarize_class("product_json", product_files),
        _summarize_class("research", research_files),
        _summarize_class("price_csv", price_files),
        _summarize_class("raw_data", raw_data_files),
    ]

    total_files = sum(c["file_count"] for c in classes)
    total_bytes = sum(c["total_size_bytes"] for c in classes)
    total_daily = sum(
        c["estimated_daily_growth_bytes"]
        for c in classes
        if c["estimated_daily_growth_bytes"] is not None
    )
    total_daily_note = "not all classes have spans > 1d" if any(
        c["estimated_daily_growth_bytes"] is None
        for c in classes
    ) else "all classes have ≥ 1d span"

    return {
        "report_generated_at": datetime.now(timezone.utc).isoformat(),
        "tool": "traderie_disk_inventory.py",
        "mode": "dry-run",
        "data_root": str(DATA_DIR),
        "total_files": total_files,
        "total_size_bytes": total_bytes,
        "total_size_human": _human_size(total_bytes),
        "estimated_total_daily_growth_bytes": round(total_daily, 2),
        "estimated_total_daily_growth_human": _human_size(total_daily),
        "estimated_daily_growth_note": total_daily_note,
        "classes": classes,
        "immutable_classes": [
            {
                "class": "immutable_migration",
                "note": "No migration snapshots exist yet. Created at cutover.",
            },
            {
                "class": "immutable_cutover",
                "note": "No cutover snapshots exist yet. Created at authority transfer.",
            },
        ],
    }


def main():
    parser = argparse.ArgumentParser(
        description="Read-only disk inventory for Traderie artifacts."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=True,
        help="Dry-run mode (default: true). No destructive operations.",
    )
    parser.add_argument(
        "--no-dry-run",
        action="store_false",
        dest="dry_run",
        help="Disable dry-run (not implemented — no destructive mode in this task).",
    )
    parser.add_argument(
        "--pretty",
        action="store_true",
        default=True,
        help="Pretty-print JSON output (default: true).",
    )

    args = parser.parse_args()

    if not args.dry_run:
        print(json.dumps({
            "error": "No destructive mode in this task. Always use --dry-run.",
            "hint": "traderie_disk_inventory.py is read-only. Use --dry-run (default).",
        }, indent=2))
        sys.exit(1)

    report = build_report()
    indent = 2 if args.pretty else None
    print(json.dumps(report, indent=indent, default=str))


if __name__ == "__main__":
    main()
